### ISSUE TITLE
Error in m4a file check

### ISSUE THREAD

**Issue by PaulProe** [Blobfolio/righteous-mimes#1]
I have a m4a file that I download each week (Church Sermon) that comes down as a m4a file. Wordpress will not accept it for security reasons. I've tried your converter and it renames the file as an MP4 file. This is the copy from the debug. Is this a file conversion error on the supplier's side (Zoom.us) or is it a bug in the converter. If I put the 'accept all' code into my wp-config file, it uploads just fine.

?

Thanks

Paul Proefrock

VALIDATION:
  Naive Name: 5.m4a
  Naive Extension: m4a
  Naive Type: audio/mpeg
  Magic Type: video/mp4
  Best Type: video/mp4

FINAL:
  Name: 5.mp4
  Extension: mp4
  Type: video/mp4
  Code: 107

SYSTEM:
  Kernel: Linux mi3-ss49.a2hosting.com 3.10.0-962.3.2.lve1.5.28.el7.x86_64 #1 SMP Tue Jan 28 04:53:14 EST 2020 x86_64
  PHP: 7.2.30
  Modules: Core; PDO; Phar; Reflection; SPL; SimpleXML; Zend OPcache; bcmath; bz2; calendar; ctype; curl; date; dom; exif; fileinfo; filter; ftp; gd; gettext; gmp; hash; iconv; imagick; imap; intl; ionCube Loader; json; libxml; litespeed; mbstring; memcache; memcached; mysqli; mysqlnd; openssl; pcntl; pcre; pdo_mysql; pdo_pgsql; pdo_sqlite; pgsql; posix; readline; session; shmop; soap; sockets; sqlite3; standard; tidy; tokenizer; xml; xmlreader; xmlrpc; xmlwriter; xsl; zip; zlib
  WordPress: 5.4.1
  Plugins: a2-optimized [2.0.10.9.8]; akismet [4.1.5]; blob-mimes [1.1.1]; contact-form-7 [5.1.7]; content-control [1.1.4]; download-button-for-elementor [1.0.0]; elementor [2.9.8]; elementor [2.9]; elementor-pro [2.9.4]; facebook-auto-publish [2.3.1]; force-regenerate-thumbnails-master [2.0.6]; jetpack [8.5]; media-link-for-elementor-master [1.0.0]; pdf-embedder [4.6]; tablepress [1.11]; user-registration [1.8.3]; user-role-editor [4.54]; wp-meta-and-date-remover [1.7.9]; wpcf7-recaptcha [1.2.6]; wpdatatables [2.8.1]
  Theme: responsive-brix [4.8.7]

**Comment by joshstoik1** [comment]
Hi @PaulProe,

Thanks for reporting! WordPress allows both MP4 audio and video by default, so there might just be something unusual in the encodings for these files that's confusing things.

Are you able to share one of the original sermon files with me (a URL, Dropbox link, etc.)? I'd be happy to take a look and see what might be causing the issues.

**Comment by PaulProe** [comment]
Josh

Thanks for the quick reply. You may download the file at this URL: https://us02web.zoom.us/rec/play/tZUsf--qqzg3SNCS4wSDC6JwW468e_ms1ncZrvFYxUa3AHgBYVChNeAWMbaPOtapAnxWtZtDPoIFc1sT

 

Thanks,

 

Paul Proefrock

**Comment by joshstoik1** [comment]
Thanks @PaulProe , but it looks like that link is behind a password lock. Can you email me a temporary access code at hello@blobfolio.com?

**Comment by PaulProe** [comment]
Josh

It was easier & quicker to share the file thru DropBox. This is the link:

 

https://www.dropbox.com/s/ah2qmlz2oo6lxzg/GMT20200510-145044_West-Count.m4a?dl=0

 

 

Paul

**Comment by joshstoik1** [comment]
Thanks @PaulProe! I appreciate you taking the time to get me a copy of the file. That's very helpful.

So... there wasn't actually anything wrong with the encoding of that file.

PHP's `fileinfo` extension was just making some bad assumptions and `Lord of the Files` wasn't being assertive enough to override that. I added a workaround and pushed a new release of the plugin (`1.1.2`) that should fix the issue for you. (That file is being correctly handled on my test site now, at least.)

When you have a moment, please update the plugin, then try to re-upload the sermon and let me know how it goes!

**Comment by PaulProe** [comment]
Josh

Thanks for your help, the update fixed the issue.

 

Paul
