### ISSUE TITLE
Outlook msg file renamed to doc (content is still intact and good)

### ISSUE THREAD

**Issue by rvencu** [Blobfolio/righteous-mimes#2]
VALIDATION:
  Naive Name: UAT-CR1340 CRWEB_1965_Corectie-facturare-abonament-in-perioada-deco-1-1.msg
  Naive Extension: msg
  Naive Type: message/rfc822
  Magic Type: application/cdfv2
  Best Type: application/msword

FINAL:
  Name: UAT-CR1340 CRWEB_1965_Corectie-facturare-abonament-in-perioada-deco-1-1.doc
  Extension: doc
  Type: application/msword
  Code: 75

SYSTEM:
  Kernel: Linux webtop.vra.ro 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64
  PHP: 7.3.17
  Modules: Core; PDO; PDO_ODBC; Phar; Reflection; SPL; SimpleXML; Zend OPcache; apcu; bcmath; bz2; calendar; cgi-fcgi; ctype; curl; date; dba; dom; enchant; exif; fileinfo; filter; ftp; gd; gettext; gmp; hash; iconv; imap; intl; ionCube Loader; json; ldap; libxml; mbstring; memcached; mysqli; mysqlnd; odbc; openssl; pcntl; pcre; pdo_mysql; pdo_pgsql; pdo_sqlite; pgsql; posix; pspell; session; shmop; snmp; soap; sockets; sqlite3; standard; sysvmsg; sysvsem; sysvshm; tidy; tokenizer; wddx; xml; xmlreader; xmlrpc; xmlwriter; xsl; zip; zlib
  WordPress: 5.4.1
  Plugins: acf [5.8.11]; advanced-database-cleaner [3.0.0]; all-in-one-wp-migration [7.22]; all-in-one-wp-migration-file-extension [1.6]; application-passwords [0.1.1]; blob-mimes [1.1.2]; cm-tooltip-glossary [3.7.1]; flush-opcache [3.0.2]; formidable [4.04.04]; formidable-api [1.08]; formidable-logs [1.0b1]; formidable-pro [4.04.04]; frmdates [1.0.04]; frmmodal [2.0]; frmreg [2.02.02]; gutenberg [8.1.0]; import-users-from-csv [1.0.1]; members [3.0.8]; richard-rest-api [1.0]; richard-rest-api [1.0]; ultimate-addons-for-gutenberg [1.14.11]; user-switching [1.5.4]; wp-jquery-datatable-richard [2.0.1]; wp-mail-smtp [2.0.1]; wpo365-login [10.6]
  Theme: chique [1.0.1]

**Comment by rvencu** [comment]
Other msg files are correct

RE CR ESD-74 (CRWEB 2102) - Plata online neautentificat - aprobare transport in productiv.msg
Naive Extension:
msg
Naive Type:
message/rfc822
Magic Type:
application/vnd.ms-outlook
Best Type:
application/vnd.ms-outlook
FINAL
Name:
RE CR ESD-74 (CRWEB 2102) - Plata online neautentificat - aprobare transport in productiv.msg
Extension:
msg
Type:
message/rfc822
Code:
77
SYSTEM
Kernel:
Linux webtop.vra.ro 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64
PHP:
7.3.17
Modules:
Core; PDO; PDO_ODBC; Phar; Reflection; SPL; SimpleXML; Zend OPcache; apcu; bcmath; bz2; calendar; cgi-fcgi; ctype; curl; date; dba; dom; enchant; exif; fileinfo; filter; ftp; gd; gettext; gmp; hash; iconv; imap; intl; ionCube Loader; json; ldap; libxml; mbstring; memcached; mysqli; mysqlnd; odbc; openssl; pcntl; pcre; pdo_mysql; pdo_pgsql; pdo_sqlite; pgsql; posix; pspell; session; shmop; snmp; soap; sockets; sqlite3; standard; sysvmsg; sysvsem; sysvshm; tidy; tokenizer; wddx; xml; xmlreader; xmlrpc; xmlwriter; xsl; zip; zlib
WordPress:
5.4.1
Plugins:
acf [5.8.11]; advanced-database-cleaner [3.0.0]; all-in-one-wp-migration [7.22]; all-in-one-wp-migration-file-extension [1.6]; application-passwords [0.1.1]; blob-mimes [1.1.2]; cm-tooltip-glossary [3.7.1]; flush-opcache [3.0.2]; formidable [4.04.04]; formidable-api [1.08]; formidable-logs [1.0b1]; formidable-pro [4.04.04]; frmdates [1.0.04]; frmmodal [2.0]; frmreg [2.02.02]; gutenberg [8.1.0]; import-users-from-csv [1.0.1]; members [3.0.8]; richard-rest-api [1.0]; richard-rest-api [1.0]; ultimate-addons-for-gutenberg [1.14.11]; user-switching [1.5.4]; wp-jquery-datatable-richard [2.0.1]; wp-mail-smtp [2.0.1]; wpo365-login [10.6]
Theme:
chique [1.0.1]

**Comment by rvencu** [comment]
At this stage I suspect the Outlook version that exported the first file is old, the second file is exported with contemporary Outlook 365

**Comment by rvencu** [comment]
> At this stage I suspect the Outlook version that exported the first file is old, the second file is exported with contemporary Outlook 365

Not true, version difference is minor... Something inside the file content is different.

**Comment by joshstoik1** [comment]
Hi @rvencu,

Thanks for reporting the issue!

The `application/CDVF2[…]` pseudo-type is something that gets assigned to all sorts of different Microsoft-generated documents when those documents contain encrypted data. I haven't personally encountered one from Outlook before, but it fits. Haha.

Is there any way you could send me a copy of that file for testing (or export a dummy message with the same settings and CDVF2 behavior)? You can shoot me a private download link at josh@blobfolio.com to keep it off the public issue page.

If the content is too sensitive or you don't have the access to do that, no worries. It's just easier when there's a known file to test workarounds against. :wink:

**Comment by rvencu** [comment]
Thanks sent it from my business email few seconds ago.

**Comment by joshstoik1** [comment]
Thank you @rvencu!

Indeed, this file's header bytes identify it as an `application/CDFV2-corrupt` file rather than an `application/vnd.ms-outlook` file.

Thankfully, the same workarounds used for other Microsoft Office file types work — at least in my test environment — for encrypted `msg` files too, so getting a fix out was relatively easy.

When you have a moment, please try updating your site's copy of `Lord of the Files` to `1.1.3` and then give the message upload another shot. (Just be sure the copy you upload has the original `.msg` extension or WordPress will likely keep it as a `.doc`.) Oh, and please let me know how it goes!

Thanks again for taking the time to do this back-and-forth. It's a pain. But if one person has this problem, hundreds probably do, and many of them probably have no idea where to even begin. :wink:

**Comment by rvencu** [comment]
Thanks, after update / clearing server cache it went through

VALIDATION:
  Naive Name: UAT-CR1340 CRWEB_1965_Corectie-facturare-abonament-in-perioada-deco-1-1.msg
  Naive Extension: msg
  Naive Type: application/vnd.ms-outlook
  Magic Type: application/cdfv2
  Best Type: application/vnd.ms-outlook

FINAL:
  Name: UAT-CR1340 CRWEB_1965_Corectie-facturare-abonament-in-perioada-deco-1-1.msg
  Extension: msg
  Type: application/vnd.ms-outlook
  Code: 77

SYSTEM:
  Kernel: Linux webtop.vra.ro 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64
  PHP: 7.3.17
  Modules: Core; PDO; PDO_ODBC; Phar; Reflection; SPL; SimpleXML; Zend OPcache; apcu; bcmath; bz2; calendar; cgi-fcgi; ctype; curl; date; dba; dom; enchant; exif; fileinfo; filter; ftp; gd; gettext; gmp; hash; iconv; imap; intl; ionCube Loader; json; ldap; libxml; mbstring; memcached; mysqli; mysqlnd; odbc; openssl; pcntl; pcre; pdo_mysql; pdo_pgsql; pdo_sqlite; pgsql; posix; pspell; session; shmop; snmp; soap; sockets; sqlite3; standard; sysvmsg; sysvsem; sysvshm; tidy; tokenizer; wddx; xml; xmlreader; xmlrpc; xmlwriter; xsl; zip; zlib
  WordPress: 5.4.1
  Plugins: acf [5.8.11]; advanced-database-cleaner [3.0.0]; all-in-one-wp-migration [7.22]; all-in-one-wp-migration-file-extension [1.6]; application-passwords [0.1.1]; blob-mimes [1.1.3]; cm-tooltip-glossary [3.7.1]; flush-opcache [3.0.2]; formidable [4.04.04]; formidable-api [1.08]; formidable-logs [1.0b1]; formidable-pro [4.04.04]; frmdates [1.0.04]; frmmodal [2.0]; frmreg [2.02.02]; gutenberg [8.1.0]; import-users-from-csv [1.0.1]; members [3.0.8]; richard-rest-api [1.0]; richard-rest-api [1.0]; ultimate-addons-for-gutenberg [1.14.11]; user-switching [1.5.4]; wp-jquery-datatable-richard [2.0.1]; wp-mail-smtp [2.0.1]; wpo365-login [10.6]
  Theme: chique [1.0.1]

**Comment by rvencu** [comment]
So, I also take this opportunity to praise your work. Glad to stumble upon it 👍
Thanks a lot.

**Comment by joshstoik1** [comment]
Excellent! I'm glad to hear it is working for you!
