### ISSUE TITLE
UTF-8 CSV Rejected by Lord of The Files, Fine when plugin Inactive

### ISSUE THREAD

**Issue by cangevendi** [Blobfolio/righteous-mimes#6]
VALIDATION:
  Naive Name: upload.csv
  Naive Extension: csv
  Naive Type: text/csv
  Magic Type: application/csv
  Best Type: 

FINAL:
  Name: upload.csv
  Extension: 
  Type: 
  Code: 64

SYSTEM:
  Kernel: Linux sg-nme-web298.main-hosting.eu 4.18.0-305.17.1.lve.el7h.x86_64 #1 SMP Wed Sep 8 04:44:37 EDT 2021 x86_64
  PHP: 8.0.7
  Modules: Core; PDO; Phar; Reflection; SPL; SimpleXML; Zend OPcache; bcmath; bz2; calendar; ctype; curl; date; dom; exif; fileinfo; filter; ftp; gd; gettext; gmp; hash; iconv; imagick; imap; intl; json; libxml; litespeed; mbstring; mysqli; mysqlnd; openssl; pcntl; pcre; pdo_mysql; pdo_sqlite; posix; readline; session; shmop; soap; sockets; sqlite3; standard; tidy; timezonedb; tokenizer; xml; xmlreader; xmlrpc; xmlwriter; xsl; zip; zlib
  WordPress: 5.9
  Plugins: blob-mimes [1.3.2]; elementor [3.5.4]; file-upload-types [1.2.2]; woocommerce [6.1.1]; yith-woocommerce-wishlist [3.5.0]
  Theme: onestore [1.2.4]

**Comment by joshstoik1** [comment]
Thanks for reporting, @cangevendi !

I pushed an update to the plugin that should fix your issue. When you have a moment, would you please retry the upload using Lord of the Files `1.3.3`?

**Comment by cangevendi** [comment]
That's so fast. Yes, it all went fine now, Thanks a lot for the update. 5 Stars.

**Comment by joshstoik1** [comment]
Woo! Thanks for confirming!
