### ISSUE TITLE
.pat and .lin files are being uploaded as a .txt

### ISSUE THREAD

**Issue by jadams-rva** [Blobfolio/righteous-mimes#8]
[extensions to add.zip](https://github.com/Blobfolio/righteous-mimes/files/12648764/extensions.to.add.zip)
Hi the company I work for wishes to upload these file types, But they both get renamed as a .txt file for me.

I believe they are used for line types and hatch patterns in autocad.

**Comment by joshstoik1** [comment]
Hi @jadams-rva ,

I think the issue is with how these file types were added to the site's allowed upload list. Try setting the MIME type for both to `text/plain`.

That should keep them from getting renamed, but let me know if that didn't work, or you're not sure what I'm talking about. :wink:
